version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  producer:
    build: ./producer
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: ./worker
    ports:
      - "6000:6000"
    depends_on:
      - redis