apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: | 
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'producer'
        static_configs:
          - targets: ['producer:80']
      - job_name: 'worker'
        static_configs:
          - targets: ['worker:80']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']